# Data below generated via the Open Trivia Database API (opentdb.com)
trivia_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "French is an official language in Canada.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Bulls are attracted to the color red.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "'Ananas' is mostly used as the word for Pineapple in other languages.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "The Sun rises from the North.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "The Lego Group was founded in 1932.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "'Club' is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Vietnam's national flag is a red star in front of a yellow background.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Slovakia is a member of European Union-", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "The mitochondria is the powerhouse of the cell.", "correct_answer": "True", "incorrect_answers": ["False"]}
    ]